exports.UPLOADS_DIRECTORY = './uploads'
exports.ADMIN_EMAIL = 'maverick.sin.0509@gmail.com'
exports.ADMIN_EMAIL_PASSWORD = 'dkaneh ahffk.'
exports.SENDGRID_USER = 'mr.new0509@gmail.com'
exports.SENDGRID_PASSWORD = 'dkaneh ahffk.MrNew0509@'
